# -*- coding: utf-8 -*-
"""sales.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yJrRMlsg_4p7dgxFDvXw0hRrwjENCKVW
"""

from google.colab import drive
drive.mount('/content/drive')

#import necessary libraray
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

#read the dataset
sales_data=pd.read_csv("drive/My Drive/techgig/train.csv")
sales_data.head()

#preprocessing
lb_make = LabelEncoder()
sales_data['Gender'] = lb_make.fit_transform(sales_data['Gender'])
sales_data.head()

X_train=sales_data[['Age']]
Y_train=sales_data[['Purchased']]
X_train.head()

Y_train.head()

#using linear model
 sale_reg = LogisticRegression(random_state=0, solver='lbfgs',multi_class='multinomial').fit(X_train, Y_train)
#sale_reg= LinearRegression().fit(X_train, Y_train)
sale_reg.score(X_train, Y_train)

#read the data of testing data
sales_test=pd.read_csv("drive/My Drive/techgig/test.csv")
sales_test.head()

#preprocessing
lb_make = LabelEncoder()
sales_test['Gender'] = lb_make.fit_transform(sales_test['Gender'])
sales_test.head()

X_test=sales_test[['Age']]
X_test.head()

#now predict the value 
y_value=sale_reg.predict(X_test)
new_df=pd.DataFrame(sales_test[['User ID']])
new_df['Purchased']=y_value
new_df.head()

new_df.to_csv('drive/My Drive/techgig/submission.csv', sep=',')

#sale_reg.decision_function(X_train)

